# Generated by Django 4.2.7 on 2023-11-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='display',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
